pwa:
    image_processor: 'pwa.image_processor.imagick'
    manifest:
        enabled: true
        background_color: "#c026d3"
        theme_color: "#c026d3"
        name: 'Symfony ToDo PWA'
        short_name: 'pwa-todo'
        description: 'stand-alone Todo list'
        orientation: "any"
        display: "standalone"
        scope: "/"
        display_override: ['fullscreen', 'minimal-ui', 'window-controls-overlay']
        id: "/"
        start_url: "/"
        icons:
            # https://www.veryicon.com/icons/miscellaneous/smart-site/noise-3.html
            - src: "task-list-svgrepo-com.svg"
              sizes: any
        screenshots:
        categories: []
        shortcuts: []
        edge_side_panel:
            preferred_width: 280
        widgets: []
    serviceworker:
        enabled: true
        src: "sw.js"
        skip_waiting: true
        workbox:
